# Generated by Django 5.1.1 on 2026-04-04 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('max_productos', models.PositiveIntegerField(blank=True, help_text='Límite de productos activos/registrados. Vacío = ilimitado', null=True)),
                ('max_usuarios_total', models.PositiveIntegerField(blank=True, help_text='Límite total de usuarios activos. Vacío = ilimitado', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='PlanRolLimite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('almacen', 'Almacén'), ('tienda', 'Tienda'), ('deposito', 'Depósito'), ('tienda_online', 'Tienda Online')], max_length=20)),
                ('max_usuarios', models.PositiveIntegerField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites_roles', to='planes.plan')),
            ],
            options={
                'verbose_name': 'Límite por rol',
                'verbose_name_plural': 'Límites por rol',
                'ordering': ['plan__codigo', 'rol'],
                'unique_together': {('plan', 'rol')},
            },
        ),
    ]
