# Generated by Django 5.1.1 on 2026-04-05 15:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0003_plan_permitemodooscuro'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='descuento_meses',
            field=models.CharField(blank=True, help_text='Meses (1-12) separados por coma donde aplica el descuento. Ej: 12', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de descuento (0-100).', max_digits=5),
        ),
        migrations.AddField(
            model_name='plan',
            name='moneda',
            field=models.CharField(default='BOB', max_length=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='precio_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio mensual del plan. Vacío = no configurado.', max_digits=10, null=True),
        ),
    ]
