# Generated by Django 5.1.1 on 2026-04-03 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '__first__'),
        ('notificaciones', '0002_alter_notificacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='empresas.empresa'),
        ),
    ]
