# Generated by Django 5.1.1 on 2026-04-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_notificacion_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('pedido', 'Pedido Recibido'), ('traspaso', 'Estado de Traspaso'), ('stock_critico', 'Stock Crítico'), ('stock_bajo', 'Stock Bajo'), ('venta', 'Venta Recibida'), ('producto_creado', 'Producto Creado'), ('producto_editado', 'Producto Editado'), ('producto_eliminado', 'Producto Eliminado'), ('precio_modificado', 'Precio Modificado'), ('pago_pendiente', 'Pago Pendiente'), ('pago_aprobado', 'Pago Aprobado'), ('pago_rechazado', 'Pago Rechazado'), ('general', 'General')], max_length=20),
        ),
    ]
