# Generated by Django 5.1.1 on 2026-04-03 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '__first__'),
        ('traspasos', '0002_remove_traspaso_fecha_aceptacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalletraspaso',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_traspasos', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='traspaso',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traspasos', to='empresas.empresa'),
        ),
    ]
