# Generated by Django 5.1.1 on 2026-04-05 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0004_pagoempresa_descuento_monto_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("asunto", models.CharField(max_length=200)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("tecnico", "Tecnico"),
                            ("facturacion", "Facturacion"),
                            ("sugerencia", "Sugerencia"),
                            ("ayuda", "Ayuda de uso"),
                        ],
                        default="tecnico",
                        max_length=20,
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("critica", "Critica"),
                        ],
                        default="media",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierto", "Abierto"),
                            ("en_proceso", "En proceso"),
                            ("respondido", "Respondido"),
                            ("cerrado", "Cerrado"),
                        ],
                        default="abierto",
                        max_length=20,
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=12, unique=True)),
                (
                    "ultimo_mensaje_por",
                    models.CharField(
                        choices=[
                            ("cliente", "Cliente"),
                            ("soporte", "Soporte"),
                            ("sistema", "Sistema"),
                        ],
                        default="cliente",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "asignado_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_asignados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket de soporte",
                "verbose_name_plural": "Tickets de soporte",
                "ordering": ["-fecha_actualizacion", "-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="MensajeTicket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "rol",
                    models.CharField(
                        choices=[("cliente", "Cliente"), ("soporte", "Soporte"), ("sistema", "Sistema")],
                        default="cliente",
                        max_length=20,
                    ),
                ),
                ("contenido", models.TextField(blank=True)),
                ("adjunto", models.FileField(blank=True, null=True, upload_to="soporte/adjuntos/")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mensajes_soporte",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mensajes_soporte",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes",
                        to="soporte.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de ticket",
                "verbose_name_plural": "Mensajes de ticket",
                "ordering": ["creado_en"],
            },
        ),
    ]
