# Generated by Django 5.1.1 on 2026-04-03 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0003_almacen_empresa_alter_almacen_nombre_and_more'),
        ('empresas', '__first__'),
        ('tiendas', '0002_remove_tienda_extra_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tiendas', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre de la Tienda'),
        ),
        migrations.AddConstraint(
            model_name='tienda',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='uniq_tienda_empresa_nombre'),
        ),
    ]
