# Generated by Django 5.1.1 on 2026-04-03 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0003_almacen_empresa_alter_almacen_nombre_and_more'),
        ('empresas', '__first__'),
        ('tiendas', '0003_tienda_empresa_alter_tienda_nombre_and_more'),
        ('vendedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendedores', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='cedula',
            field=models.CharField(max_length=50, verbose_name='Cédula/DNI'),
        ),
        migrations.AddConstraint(
            model_name='vendedor',
            constraint=models.UniqueConstraint(fields=('empresa', 'cedula'), name='uniq_vendedor_empresa_cedula'),
        ),
    ]
