# Generated by Django 5.1.1 on 2026-04-03 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '__first__'),
        ('ventas', '0005_detalleventa_cantidad_cajas_detalleventa_modalidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amortizacioncredito',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amortizaciones_credito', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_ventas', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='solicitudanulacionventa',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_anulacion', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='venta',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='empresas.empresa'),
        ),
    ]
