# Generated by Django 5.1.1 on 2026-04-03 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '__first__'),
        ('tiendas_virtuales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendavirtual',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tiendas_virtuales', to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='tiendavirtual',
            name='codigo',
            field=models.CharField(max_length=50, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tiendavirtual',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre de la Tienda Virtual'),
        ),
        migrations.AlterField(
            model_name='tiendavirtual',
            name='url',
            field=models.URLField(max_length=300, verbose_name='URL de la Tienda'),
        ),
        migrations.AddConstraint(
            model_name='tiendavirtual',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='uniq_tiendavirtual_empresa_nombre'),
        ),
        migrations.AddConstraint(
            model_name='tiendavirtual',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uniq_tiendavirtual_empresa_codigo'),
        ),
        migrations.AddConstraint(
            model_name='tiendavirtual',
            constraint=models.UniqueConstraint(fields=('empresa', 'url'), name='uniq_tiendavirtual_empresa_url'),
        ),
    ]
