# Generated by Django 5.1.1 on 2026-04-03 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoluciones', '0001_initial'),
        ('empresas', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='empresas.empresa'),
        ),
    ]
